utilisateur_homepage:
    path:     /
    defaults: { _controller: UtilisateurBundle:Default:index }
testMailer:
    path:     /testMailer
    defaults: { _controller: UtilisateurBundle:Default:testMailer }
    
logout_user:
    path:     /logoutUser
    defaults: { _controller: UtilisateurBundle:Default:logout }
    
list_of_user:
    path:     /liste_utilisateurs
    defaults: { _controller: UtilisateurBundle:Utilisateur:listUser }
    
detail_user:
    path:     /detail_utilisateur/{id}
    defaults: { _controller: UtilisateurBundle:Utilisateur:detailUser , id: 1 }

delete_user:
    path:     /deleteUser/{id}
    defaults: { _controller: UtilisateurBundle:Utilisateur:deleteUser , id: 1 }

activate_user:
    path:     /activate/{id}
    defaults: { _controller: UtilisateurBundle:Utilisateur:activateUser , id: 1 }
    
disactivate_user:
    path:     /disactivate/{id}
    defaults: { _controller: UtilisateurBundle:Utilisateur:disactivateUser , id: 1 }

  
  
Lims:
    resource: "@AnalysesBundle/Resources/config/lims/routing.yml"
    prefix:   /Lims
    
# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile