<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * DemandeAnalyseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAnalyseRepository extends \Doctrine\ORM\EntityRepository
{
}
