<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * EchantillonItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchantillonItemRepository extends \Doctrine\ORM\EntityRepository
{
}
