<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * EchantillonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EchantillonRepository extends \Doctrine\ORM\EntityRepository
{
}
