<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * ModeOperatoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeOperatoireRepository extends \Doctrine\ORM\EntityRepository
{
}
