<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * NomOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NomOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
