<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * OperationEffectueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationEffectueRepository extends \Doctrine\ORM\EntityRepository
{
}
