<?php

namespace Analyses\AnalysesBundle\Repository;

/**
 * TypeEchantillonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeEchantillonRepository extends \Doctrine\ORM\EntityRepository
{
}
